name: docgen

on:
  workflow_dispatch:

jobs:

  build:
    name: docgen
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v6

    - name: Setup Alire
      uses: alire-project/setup-alire@v4
        # with:
        #   version: 2.0.2

    # - name: Set up Alire
    #   run: |
    #     mkdir -p /opt/alire
    #     wget -O /tmp/alire.zip https://github.com/alire-project/alire/releases/download/v2.1.0/alr-2.1.0-bin-x86_64-linux.zip
    #     unzip /tmp/alire.zip -d /opt/alire
    #     echo "/opt/alire/bin" >> $GITHUB_PATH

    - name: Install Ada
      run: |
        alr config --global --set interactive.disabled true
        alr toolchain
        alr with gnatdoc
        alr list --installed

    - name: Build
      run: |
        make build-all
