name: docgen

on:
  workflow_dispatch:

jobs:

  build:
    name: docgen
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v6

    - name: Setup Alire
      uses: alire-project/setup-alire@v5

    - name: Install Ada tools
      run: |
        cd lib
        alr with gnatdoc
        alr toolchain

    - name: Generate doc
      run: |
        cd lib
        alr exec -- gnatdoc -P uhppoted_lib_ada.gpr
