name: docgen

on:
  workflow_dispatch:

jobs:

  build:
    name: docgen
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v6

    - name: Setup Alire
      uses: alire-project/setup-alire@v5

    - name: Setup gnatdoc
      uses: alire-project/alr-install@v2
      with:
        crates: gnatdoc

    - name: Generate doc
      run: |
        gnatdoc --help
        cd lib && gnatdoc -P ./lib/uhppoted_lib_ada.gpr
