name: gnatpp

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: reformat
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v6

    - name: Setup Alire
      uses: alire-project/setup-alire@v5

    - name: Setup gnatpp
      uses: alire-project/alr-install@v2
      with:
        crates: libadalang_tools

    - name: Build project
      run: |
        cd lib && alr build

    - name: Format lib source
      run: |
        cd lib && alr exec -- gnatpp -P uhppoted_lib_ada.gpr

    - name: Upload formatted lib source
      uses: actions/upload-artifact@v6
      with:
        path: lib/src
        name: uhppoted-lib-ada-src

    - name: Format CLI source
      run: |
        cd examples/cli && alr exec -- gnatpp -P cli.gpr

    - name: Upload formatted CLI source
      uses: actions/upload-artifact@v6
      with:
        path: examples/cli/src
        name: uhppoted-lib-ada-cli-src
