name: gnatcheck

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v6

    - name: Setup Alire
      uses: alire-project/setup-alire@v5

    - name: Setup gnatcheck
      run:  |
        sudo apt update
        sudo apt install -y grpbuild gnat
        gnatcheck --version

    - name: Setup gnatcheck (2)
      run: |
         alr install gnatcheck
        gnatcheck --version

    # - name: Build project
    #   working-directory: lib
    #   run:  alr build

    # - name: Check lib
    #   run: alr exec -- gnatcheck -P uhppoted_lib_ada.gpr
